from .wavelets import peak_detection
from .similarity import windowed_cross_correlation_lagged_one_sided, windowed_cross_correlation_lagged_two_sided
from .basics import outlier_detectionMAD, outlier_detectionIQR, log_transform